Deleting more objects
krkn-chaos/krkn-lib pull request #47
Opened 2023-09-21 15:19 UTC by paigerube14

Moving changes from [pr](https://github.com/redhat-chaos/krkn-lib/pull/44) to branch in redhat-chaos org to be able to run with secrets

2023-09-21 15:21 UTC, chaitanyaenr approved these changes
LGTM!

2023-09-22 06:08 UTC, tsebastiani requested changes
Hi Paige,
Would be great if you could:

- add  unit tests to the methods that you added otherwise the coverage will drop ( I know that sometimes may feel odd to write tests to small methods with an obvious outcome, but we've to try to keep the coverage high)
- add types to the method parameters as well to align with the lib convention
- add some pydoc to the methods so the doc website will be populated properly.

added some comments in the code as well

Thanks a lot!

2023-09-22 06:36 UTC, tsebastiani commented on src/krkn_lib/k8s/krkn_kubernetes.py
> +        ret = self.apps_api.list_namespaced_deployment(namespace, pretty=True)
not catching exception

2023-10-04 17:52 UTC, paigerube14 commented
@tsebastiani @chaitanyaenr can you ptal, I have updated with pydoc and tests

2023-10-04 21:06 UTC, chaitanyaenr commented on pyproject.toml
> +kubernetes ="^28.1.0"
Hitting the following during the install:
```
The conflict is caused by:
    The user requested kubernetes
    krkn-lib 0.0.0 depends on kubernetes<29.0.0 and >=28.1.0
    arcaflow-plugin-kill-pod 0.0.0 depends on kubernetes<27.0.0 and >=26.1.0
```

2023-10-05 15:35 UTC, tsebastiani approved these changes

2023-10-05 15:36 UTC, merged